export { createAuth } from './better-auth.config.js'
export type { Auth } from './better-auth.config.js'
export { createCachedPermissionResolver } from './server/permission-cache.js'
export type { RolesPermissionSource } from './server/permission-cache.js'
export { createDeletedAtCheckHook } from './hooks/deleted-at-check.js'
export { createLoginAuditHook } from './hooks/login-audit.js'
export { createPermissionResolver } from './permissions.js'
export type { PermissionResolver } from './permissions.js'
export { getSession, requireSession, getCurrentUser } from './session-helpers.js'
export { UnauthorizedError } from './unauthorized-error.js'
