export {
  DomaceClaimAmountInputSchema,
  DomaceClaimChangeOutcomeInputSchema,
  DomaceClaimCreateInputSchema,
  DomaceClaimDetailSchema,
  DomaceClaimFaultInputSchema,
  DomaceClaimFaultItemSchema,
  DomaceClaimListItemSchema,
  DomaceClaimListQuerySchema,
  DomaceClaimUpdateInputSchema,
  type DomaceClaimAmountInput,
  type DomaceClaimChangeOutcomeInput,
  type DomaceClaimCreateInput,
  type DomaceClaimDetail,
  type DomaceClaimFaultInput,
  type DomaceClaimFaultItem,
  type DomaceClaimListItem,
  type DomaceClaimListQuery,
  type DomaceClaimListResponse,
  type DomaceClaimUpdateInput,
} from '@mr/shared'
